// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LightBoxController from "./light_box_controller.js"
application.register("light-box", LightBoxController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import RemovalsController from "./removals_controller.js"
application.register("removals", RemovalsController)

import SwiperController from "./swiper_controller.js"
application.register("swiper", SwiperController)

import TomSelectAmenitiesController from "./tom_select_amenities_controller.js"
application.register("tom-select-amenities", TomSelectAmenitiesController)

import TomSelectFacilitiesController from "./tom_select_facilities_controller.js"
application.register("tom-select-facilities", TomSelectFacilitiesController)

import TomSelectSuitabilitiesController from "./tom_select_suitabilities_controller.js"
application.register("tom-select-suitabilities", TomSelectSuitabilitiesController)
